app = "feedbackbot"

[build]

[processes]
app = "python bot.py"

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]